version: '3.8'

services:
  # Frontend Service
  frontend:
    build:
      context: ./todo-frontend 
    ports:
      - "4200:4200"
    restart: always
    depends_on:
      - backend
    command: npm start

  # Backend Service
  backend:
    build:
      context: ./todo-backend  
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DATABASE_NAME: todo_database
    command: npm run start

  # MySQL Database Service
  database:
    image: mysql:latest
    ports:
      - "3366:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo_database
      MYSQL_USER: rootusr
      MYSQL_PASSWORD: root
