version: '3.8'

services:

  # Frontend Service
  frontend:
    build:
      context: ./todo-frontend 
    ports:
      - 4200:4200
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start

  # Backend Service
  backend:
    build:
      context: ./todo-backend  
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      DATABASE_URL: postgres://root:rootpw@postgres:5432/db
    command: npm run start

  # Postgres Database Service
  database:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: rootpw
      POSTGRES_USER: root
      POSTGRES_DB: db
    ports:
      - "5432:5432"